# coding: utf-8

# flake8: noqa
"""
    Users

    Microservice that provide users' data management.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from monolith.swagger_client.models.new_user import NewUser
from monolith.swagger_client.models.report import Report
from monolith.swagger_client.models.user import User
